name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the client image
      - name: Build and Push Client Image
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/Dockerfile.client
          push: true
          tags: ghcr.io/bdot-real/sponsorship-client:latest

      # Build and push the server image
      - name: Build and Push Server Image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile.server
          push: true
          tags: ghcr.io/bdot-real/sponsorship-server:latest
